-- Seed data for local development
-- This file is run automatically after migrations

-- Create test users
INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, created_at, updated_at)
VALUES 
    ('11111111-1111-1111-1111-111111111111', 'homeowner@example.com', crypt('password123', gen_salt('bf')), NOW(), NOW(), NOW()),
    ('22222222-2222-2222-2222-222222222222', 'contractor1@example.com', crypt('password123', gen_salt('bf')), NOW(), NOW(), NOW()),
    ('33333333-3333-3333-3333-333333333333', 'contractor2@example.com', crypt('password123', gen_salt('bf')), NOW(), NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Create test contractors
INSERT INTO contractors (id, user_id, business_name, license_number, categories, verified, rating)
VALUES
    ('44444444-4444-4444-4444-444444444444', '22222222-2222-2222-2222-222222222222', 'ABC Construction', 'LIC-12345', '{renovation,repair}', true, 4.5),
    ('55555555-5555-5555-5555-555555555555', '33333333-3333-3333-3333-333333333333', 'XYZ Builders', 'LIC-67890', '{new_construction,renovation}', true, 4.8)
ON CONFLICT (id) DO NOTHING;

-- Create sample projects
INSERT INTO projects (id, owner_id, title, description, status)
VALUES
    ('66666666-6666-6666-6666-666666666666', '11111111-1111-1111-1111-111111111111', 'Kitchen Renovation', 'Complete kitchen remodel including cabinets, countertops, and appliances', 'active'),
    ('77777777-7777-7777-7777-777777777777', '11111111-1111-1111-1111-111111111111', 'Bathroom Repair', 'Fix leaking shower and replace vanity', 'draft')
ON CONFLICT (id) DO NOTHING;

-- Create sample bid cards
INSERT INTO bid_cards (id, project_id, category, job_type, budget_range, timeline, ai_confidence, status)
VALUES
    ('88888888-8888-8888-8888-888888888888', '66666666-6666-6666-6666-666666666666', 'renovation', 'kitchen_remodel', '{"min": 20000, "max": 35000, "currency": "USD"}', '4-6 weeks', 0.92, 'final'),
    ('99999999-9999-9999-9999-999999999999', '77777777-7777-7777-7777-777777777777', 'repair', 'bathroom_plumbing', '{"min": 2000, "max": 5000, "currency": "USD"}', '1-2 weeks', 0.88, 'draft')
ON CONFLICT (id) DO NOTHING;

-- Create sample messages
INSERT INTO messages (project_id, sender_role, sender_id, content)
VALUES
    ('66666666-6666-6666-6666-666666666666', 'homeowner', '11111111-1111-1111-1111-111111111111', 'I need help renovating my kitchen'),
    ('66666666-6666-6666-6666-666666666666', 'agent', NULL, 'I can help you with your kitchen renovation. Let me ask you a few questions to better understand your needs.'),
    ('66666666-6666-6666-6666-666666666666', 'agent', NULL, 'What is your budget range for this project?'),
    ('66666666-6666-6666-6666-666666666666', 'homeowner', '11111111-1111-1111-1111-111111111111', 'My budget is between $20,000 and $35,000')
ON CONFLICT DO NOTHING;

-- Create sample user preferences
INSERT INTO user_preferences (user_id, preference_key, preference_value, confidence)
VALUES
    ('11111111-1111-1111-1111-111111111111', 'default_budget', '{"min": 10000, "max": 50000, "currency": "USD"}', 0.9),
    ('11111111-1111-1111-1111-111111111111', 'preferred_timeline', '"flexible"', 0.8),
    ('11111111-1111-1111-1111-111111111111', 'location', '{"city": "San Francisco", "state": "CA", "zip": "94105"}', 1.0)
ON CONFLICT (user_id, preference_key) DO NOTHING;

-- Add some sample knowledge base entries
INSERT INTO project_knowledge (content, source_type, metadata)
VALUES
    ('Kitchen renovations typically cost between $12,000 and $35,000 for a medium-sized kitchen', 'pricing', '{"category": "renovation", "job_type": "kitchen"}'),
    ('Bathroom repairs for plumbing issues usually range from $1,000 to $5,000 depending on severity', 'pricing', '{"category": "repair", "job_type": "bathroom"}'),
    ('California requires contractors to have a valid license for jobs over $500', 'regulation', '{"state": "CA", "requirement": "license"}')
ON CONFLICT DO NOTHING;

-- Note: Vector embeddings for project_knowledge would be generated by the application
-- This seed file only creates the text content